name: Binance Script

on:
  schedule:
    - cron: "30 */4 * * *"   # chạy mỗi 4 giờ
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: python script.py
